### ISSUE TITLE
Common.Logging + Numeric Formating +  ElasticSearch Sink => Nummeric fields in Elastic

### ISSUE THREAD

**Issue by pardahlman** [CaptiveAire/Common.Logging.Serilog#11]
A typical (I suppose?) set-up is using this Common Logging adapter for Serilog and then having Serilog sink to Elastic with the [serilog-sinks-elasticsearch](https://github.com/serilog/serilog-sinks-elasticsearch). However, looking at the [source code in `SerilogCommonLogger.cs`](https://github.com/CaptiveAire/Common.Logging.Serilog/blob/master/src/SerilogCommonLogger.cs#L612), it looks like we're replacing a "numeric formatted string" (like `This formatted string is {0}`) with the "Serilog formatted string" (like `This formatted string is {@0}`), which will make `fields.0` appear as an indexed field in Elastic.

There is an [related  issue with the elastic sink](https://github.com/serilog/serilog/issues/462), but I think we could handle it pretty nicely here by simply evaluate all numeric formatted parameters in [the `WriteFormat` method of `SerilogCommonLogger.cs`](https://github.com/CaptiveAire/Common.Logging.Serilog/blob/master/src/SerilogCommonLogger.cs#L612) before passing them to the Serilog. This would be done by

1. Look at the string format pattern, if does not start with `{@ }` replace it with the value of the arg
2. If it starts with `{@ }` pass it down to the `_logger`.

**Comment by Jaben** [comment]
Nuget updated. Thanks!
