### ISSUE TITLE
Numeric strings are not correct formatted

### ISSUE THREAD

**Issue by pardahlman** [CaptiveAire/Common.Logging.Serilog#13]
There was a bug introduced in pull request #12 (_Preformat numeric formatted arguments before passing string to Serilogger_) that causes string with more than one numeric argument to be wrongly pre-formatted.

The reason is that we manipulate the string from left-to-right and at the same time uses the char indexes from the matcher in the original template string. If the arg's value has more chars than the formatter itself (which is very likely) we will insert the following matchers based on an old index rather than the new one. The solution is to change the string from right-to-left.

**Comment by Jaben** [comment]
k, merged and will release nuget today.
