### ISSUE TITLE
Serilog 2.0 update

### ISSUE THREAD

**Issue by nblumhardt** [CaptiveAire/Common.Logging.Serilog#17]
Howdy!

I'm working on a PR to update this library to work with Serilog 2.

https://github.com/serilog/serilog/issues/802

Let me know if I've been beaten to it, or if you see any issues.

Cheers!

**Comment by nblumhardt** [comment]
Ah, I see I have! How did I miss: https://github.com/CaptiveAire/Common.Logging.Serilog/pull/16 -- sorry! :-)

**Comment by Jaben** [comment]
No worries :)
