### ISSUE TITLE
Creating a logger by string name instead of type breaks serilog MinimumLevel.Override

### ISSUE THREAD

**Issue by oltronix** [CaptiveAire/Common.Logging.Serilog#23]
When using the string overload of GetLogger the sourceContext is never set on the LogEvent, which causes issues with the MinimumLevel.Override("loggername", Level) feature available when configuring seriLog.

This complicates logging in cases where we are interested in lower level logs for some packages which are using the string overload to create their loggers. The issue is easily fixed by changing the "NamedContext" string in SerilogFactoryAdapter.cs, but I'm unsure if that could cause other issues?

```
public ILog GetLogger(string name)
        {
            return new SerilogCommonLogger(new SerilogInstanceWrapper(l =>
                 l.ForContext("NamedContext", name), _logger));
        }


public ILog GetLogger(string name)
        {
            return new SerilogCommonLogger(new SerilogInstanceWrapper(l => l.ForContext("SourceContext", name), _logger));
        }
```

**Comment by Jaben** [comment]
Merged and released to nuget -- thanks for the PR!
