### ISSUE TITLE
Its not logging using logger which i have created from Common.Logging LogManager

### ISSUE THREAD

**Issue by miralpopat** [CaptiveAire/Common.Logging.Serilog#6]
ILog log1 = LogManager.GetLogger("logger1");

_log = new LoggerConfiguration()
                .Destructure.UsingAttributes()
                .WriteTo.Console()
                .WriteTo.Seq("http://localhost:5341")
                .WriteTo.Elasticsearch(new ElasticsearchSinkOptions(new Uri("http://localhost:9200/"))
                {
                   IndexFormat = "hackingdemo-{0:yyyy.MM.dd}"
                })
                .CreateLogger();
            
            Log.Logger = _log;

log1.Info("{ x: 5, y: 8}"); // This line doesn't logs

**Comment by Jaben** [comment]
The global serilog instance must be available before calling the common log serilog adapter.

e.g.

```
Log.Logger = new LoggerConfiguration().WriteTo.Console().CreateLogger();                        	

LogManager.Adapter = new Common.Logging.Serilog.SerilogFactoryAdapter();

ILog log1 = LogManager.GetLogger<SerilogFactoryAdapter>();	
	
log1.Info("{ x: 5, y: 8}");
```

I'll make some changes to improve this situation.

**Comment by Jaben** [comment]
Issue should be fixed in latest version released today. Now the Serilog global instance is Lazy Loaded and will ignore the Serilog "Silent Logger" (which means it' not configured yet).
