### ISSUE TITLE
Update to Common.Logging 3.0

### ISSUE THREAD

**Issue by richardlawley** [CaptiveAire/Common.Logging.Serilog#7]
Since Common.Logging has been updated to 3.0.0, this library is no longer compatible.  Could it be rebuilt against 3.0.0 please?

**Comment by Jaben** [comment]
They changed the ILog API and added an abstraction of Log4Net context variables. I currently don't have the time to update to support that new API -- but I'd accept a pull request in the short term. In the long time, I'll carve out some time to take a stab at it.

**Comment by Jaben** [comment]
Nuget updated with Common Logging 3 support.
